#include "rmw_dds_common/msg/Gid.idl"
#include "rmw_dds_common/msg/NodeEntitiesInfo.idl"

module rmw_dds_common {
  module msg {
    struct ParticipantEntitiesInfo {
        @key
        rmw_dds_common::msg::Gid gid;
        sequence<rmw_dds_common::msg::NodeEntitiesInfo, 1024> node_entities_info_seq;
    };
  };
};
